name: Publish Website

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🚀 Deploy Website Every Commit
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get Latest Code
      uses: actions/checkout@v3

    - name: 📂 Sync Files
      uses: SamKirkland/web-deploy@v1
      with:
        target-server: cirt.sigmoid.site
        remote-user: sigmtlbn
        private-ssh-key: ${{ secrets.SSH_KEY }}
        destination-path: /home/sigmtlbn/cirt.sigmoid.site/wp-content/themes/mkd-cirt/
        rsync-options: "-e 'ssh -p 21098'"
